#spring.application.name=book-network-api

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json

application:
  security:
    jwt:
      secret-key: "ULyJQmjWnjwC8a0j6cp8CtI/lbFMSeciKjlgyiESbvYJWol8VaQHuKxpNT3AXLQU"
      expiration: 8640000


server:
  servlet:
    context-path: /api/v1/
