spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: username
    passwors: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: maxi
    password: maxwell22
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

# For best practices, we need to store our secrete key
# in the app yml file for security reasons.
application:
  security:
    jwt:
      secret-key: ULyJQmjWnjwC8a0j6cp8CtI/lbFMSeciKjlgyiESbvYJWol8VaQHuKxpNT3AXLQU
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
server:
  port: 8088
